# Generated by Django 5.1.1 on 2024-10-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_wateringcan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateringcan',
            name='name',
            field=models.CharField(default='Лейка', max_length=100),
        ),
    ]
