# Generated by Django 5.1.1 on 2024-10-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_wateringcan_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wateringcan',
            old_name='heigth',
            new_name='height',
        ),
    ]
