# Generated by Django 5.1.1 on 2024-11-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_heigth_wateringcan_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wateringcan',
            name='height',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wateringcan',
            name='length',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wateringcan',
            name='nose_length',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wateringcan',
            name='width',
            field=models.IntegerField(max_length=100),
        ),
    ]
