# Generated by Django 5.1.1 on 2024-11-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_wateringcan_height_alter_wateringcan_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wateringcan',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wateringcan',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wateringcan',
            name='nose_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wateringcan',
            name='width',
            field=models.IntegerField(),
        ),
    ]
